---
- name: Deploy Traefik
  hosts: nodes
  roles:
    - traefik

- name: Deploy Xray
  hosts: nodes
  roles:
    - xray

- name: Deploy CoreDNS
  hosts: nodes
  roles:
    - coredns

- name: Deploy DoH Server
  hosts: nodes
  roles:
    - doh-server
